/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as DieselRouteImport } from './routes/diesel'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SpotRouteImport } from './routes/spot'
import { Route as ApiDailyRouteImport } from './routes/api/daily'
import { Route as BriefSlugRouteImport } from './routes/brief/$slug'
import { Route as DeskDeskRouteImport } from './routes/desk/$desk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const DieselRoute = DieselRouteImport.update({
  id: '/diesel',
  path: '/diesel',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotRoute = SpotRouteImport.update({
  id: '/spot',
  path: '/spot',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyRoute = ApiDailyRouteImport.update({
  id: '/api/daily',
  path: '/api/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefSlugRoute = BriefSlugRouteImport.update({
  id: '/brief/$slug',
  path: '/brief/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskDeskRoute = DeskDeskRouteImport.update({
  id: '/desk/$desk',
  path: '/desk/$desk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/diesel': typeof DieselRoute
  '/glossary': typeof GlossaryRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/spot': typeof SpotRoute
  '/subscribe': typeof SubscribeRoute
  '/api/daily': typeof ApiDailyRoute
  '/brief/$slug': typeof BriefSlugRoute
  '/desk/$desk': typeof DeskDeskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/diesel': typeof DieselRoute
  '/glossary': typeof GlossaryRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/spot': typeof SpotRoute
  '/subscribe': typeof SubscribeRoute
  '/api/daily': typeof ApiDailyRoute
  '/brief/$slug': typeof BriefSlugRoute
  '/desk/$desk': typeof DeskDeskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/diesel': typeof DieselRoute
  '/glossary': typeof GlossaryRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/spot': typeof SpotRoute
  '/subscribe': typeof SubscribeRoute
  '/api/daily': typeof ApiDailyRoute
  '/brief/$slug': typeof BriefSlugRoute
  '/desk/$desk': typeof DeskDeskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/diesel'
    | '/glossary'
    | '/saved'
    | '/search'
    | '/spot'
    | '/subscribe'
    | '/api/daily'
    | '/brief/$slug'
    | '/desk/$desk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/diesel'
    | '/glossary'
    | '/saved'
    | '/search'
    | '/spot'
    | '/subscribe'
    | '/api/daily'
    | '/brief/$slug'
    | '/desk/$desk'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/diesel'
    | '/glossary'
    | '/saved'
    | '/search'
    | '/spot'
    | '/subscribe'
    | '/api/daily'
    | '/brief/$slug'
    | '/desk/$desk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  DieselRoute: typeof DieselRoute
  GlossaryRoute: typeof GlossaryRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SpotRoute: typeof SpotRoute
  SubscribeRoute: typeof SubscribeRoute
  ApiDailyRoute: typeof ApiDailyRoute
  BriefSlugRoute: typeof BriefSlugRoute
  DeskDeskRoute: typeof DeskDeskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diesel': {
      id: '/diesel'
      path: '/diesel'
      fullPath: '/diesel'
      preLoaderRoute: typeof DieselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spot': {
      id: '/spot'
      path: '/spot'
      fullPath: '/spot'
      preLoaderRoute: typeof SpotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily': {
      id: '/api/daily'
      path: '/api/daily'
      fullPath: '/api/daily'
      preLoaderRoute: typeof ApiDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$slug': {
      id: '/brief/$slug'
      path: '/brief/$slug'
      fullPath: '/brief/$slug'
      preLoaderRoute: typeof BriefSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/$desk': {
      id: '/desk/$desk'
      path: '/desk/$desk'
      fullPath: '/desk/$desk'
      preLoaderRoute: typeof DeskDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  DieselRoute: DieselRoute,
  GlossaryRoute: GlossaryRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SpotRoute: SpotRoute,
  SubscribeRoute: SubscribeRoute,
  ApiDailyRoute: ApiDailyRoute,
  BriefSlugRoute: BriefSlugRoute,
  DeskDeskRoute: DeskDeskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
